#!/bin/bash

## #ddev-generated
## Description: Shows local exposed ports for 'ddev platform tunnel:open'
## Usage: platform:ports
## Example: ddev platform:ports

[[ -f .ddev/.env ]] && source .ddev/.env
PORTS=$(seq 30000 ${DDEV_PLATFORMSH_LITE_TUNNEL_UPPER_RANGE-30001})
for i in $PORTS; do
  CONTAINER_PORT=$(~/.ddev/bin/docker-compose -f .ddev/.ddev-docker-compose-full.yaml port web $i)
  echo "$i -> $CONTAINER_PORT"
done
