ahoyapi: v2
commands:
  readme:
    usage: 'Tidy up README.md'
    cmd: |
      prettier README.md --write
      markdown-toc -i README.md

  readme:watch:
    usage: 'Watch README.md for changes'
    cmd: |
      node watch.js
