#ddev-generated
# To upgrade: ddev get https://github.com/hanoii/ddev-platformsh-lite/tarball/master
# If you wish to maintain this file differently, remove #ddev-generated above.
# @see https://github.com/hanoii/ddev-platformsh-lite
web_environment:
  # Avoid checking for updates, as it will be updated on start.
  - PLATFORMSH_CLI_UPDATES_CHECK=0
hooks:
  post-start:
    # Update cli to the latest version
    - exec: 'platform self:update -qy --no-major || true'
    # Install shell integration to avoid prompt
    - exec: 'platform self:install -qy || true'
    - exec: '([ ! -z "${PLATFORMSH_CLI_TOKEN:-}" ] && platform ssh-cert:load -y) || true'
    - exec: '([ ! -z "${PLATFORMSH_CLI_TOKEN:-}" ] && platform drush-aliases -r -g ${DDEV_PROJECT} -y) || true'
